apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
