apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  url: https://nvidia.github.io/k8s-device-plugin
  interval: 1h
