apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-sealed
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 10m0s
  path: ./infrastructure/sealed-dependent
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
