apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mlflow
  namespace: mlflow
spec:
  dependsOn:
    - name: postgres
      namespace: postgres
  releaseName: mlflow
  targetNamespace: mlflow
  interval: 1h # Helm CRD drift detection interval
  chart:
    spec:
      chart: mlflow
      version: "0.7.19"
      interval: 10h # Interval for Helm chart updates
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: mlflow
  values:
    # Backend store configuration for PostgreSQL
    backendStore:
      postgres: # Sadly, this Helm chart does not seem to work with the existingDatabaseSecret
        enabled: true
        host: "postgres-postgresql.postgres.svc.cluster.local"
        port: 5432
        database: "mlflow"
        user: "mlflow"
        password: "CcanvylkFK5C&5wWZI"
      databaseMigration: false
      databaseConnectionCheck: true

    # Artifact storage (using default file system for now)
    artifactRoot:
      defaultArtifactRoot: "/mlflow/artifacts"
      defaultArtifactsDestination: "/mlflow/artifacts"

    # Service configuration
    service:
      type: ClusterIP
      port: 5000
      name: http
      enabled: true

    # Resource limits
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 2Gi