apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab
  namespace: jupyterlab
  labels:
    app: jupyterlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox:1.36
        command: ['sh', '-c', 'chown -R 1000:100 /home/jovyan/work && chmod -R 755 /home/jovyan/work']
        volumeMounts:
        - name: jupyter-data
          mountPath: /home/jovyan/work
        securityContext:
          runAsUser: 0
      containers:
      - name: jupyterlab
        image: rhprasad/jupyter-scipy-mlflow:latest
        ports:
        - containerPort: 8888
          name: https
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: JUPYTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: jupyterlab-credentials
              key: token
        - name: GEN_CERT
          value: "no"
        command: ["start-notebook.py"]
        args:
        - "--certfile=/etc/ssl/certs/tls.crt"
        - "--keyfile=/etc/ssl/private/tls.key"
        - "--ip=0.0.0.0"
        - "--port=8888"
        - "--no-browser"
        - "--allow-root"
        volumeMounts:
        - name: jupyter-data
          mountPath: /home/jovyan/work
        - name: ssl-certs
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: ssl-private
          mountPath: /etc/ssl/private
          readOnly: true
        # - name: shared-data
        #   mountPath: /data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: jupyter-data
        persistentVolumeClaim:
          claimName: jupyterlab-pvc
      - name: ssl-certs
        secret:
          secretName: jupyterlab-tls-secret
          items:
          - key: tls.crt
            path: tls.crt
      - name: ssl-private
        secret:
          secretName: jupyterlab-tls-secret
          items:
          - key: tls.key
            path: tls.key
      # - name: shared-data
      #   persistentVolumeClaim:
      #     claimName: shared-data-pvc
