apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab-pvc
  namespace: jupyterlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-csi-iscsi-retain
  resources:
    requests:
      storage: 10Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: shared-data-pvc
#   namespace: jupyterlab
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: synology-nfs-storage
#   resources:
#     requests:
#       storage: 50Gi
