apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: synology
spec:
  releaseName: synology-csi
  targetNamespace: synology
  interval: 1h # Helm CRD drift detection interval
  chart:
    spec:
      chart: synology-csi
      version: 0.10.1
      interval: 10h # Interval for Helm chart updates
      sourceRef:
        kind: HelmRepository
        name: synology
        namespace: synology
  values:
    clientInfoSecret:
      name: synology-csi-client-info
