# Ripped from ChatGPT
# postgres-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      version: 16.7.21
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  releaseName: postgresql
  targetNamespace: default
  values:
    auth:
      username: admin
      password: admin
      database: postgres
    primary:
      persistence:
        enabled: true
        size: 8Gi
