# Ripped from ChatGPT
# postgres-helmrepository.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
  interval: 10m
