# Ripped from ChatGPT
# postgres-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: default  # or another namespace
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 16.7.21   # pin to a specific version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: admin
      password: admin
      database: postgres
    primary:
      persistence:
        enabled: true
        size: 8Gi
