apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mcpo-credentials
  namespace: mcpo
spec:
  encryptedData:
    api-key: AgB9lKnAoJnvdHCgmXnNsyISRzTN/PZEopp08e42YLaAeRdndUOQT2R2BZhII5tf75U0qjtqjC//RVeoNK7Dm4V33PxfQMss0+QOgUPUoQ1e08UURyPDwBrw3a3Z/plpxvOzN76/kV7XwQScae6bRuIA7/8IGZh+wlbJIqDGBxFuXRO/o2bW/jYd4mdsUJvJaJ5xC2WX2+ogssxSfILK2g0wVaMTGqVjOHnaLfasytnjSeCSpyc/mBExWKN+6FdbLieecrUEBWYKpJsz5XOWVCIegVqSQM/ZAa7vtomlshoCpaNogWTgLsLeeCAXOPEfibEZFqEBCcPmW7KubHbDNoDmOgffNW+x2hrN2jsy7WvohhQzm9KuHXx4Tsk6QmxAKOg4XgEs9/hlz7pkge/l/LvuS3F5jp8VGesUrHW/2UIP0PzXFP/qeWPpbxNAmeDEdAOeZpUH1sJiWMwkGsSx1EF7JZ+w1rxNzY0wRpHGWrH/HxouZw0GeK1OeY4ZMM5ZwNnwQ2parv1wc9o4/KstXhtQLcjdj21wEkjtFgGqbkrkGo9s88zB9maF4t88fYqauDMKLtWNav2gp0X9QNQ8F34p9xi26+sH/mTT7aHzx1TI3/82dSc2/Fd3NBs13yY9J5BzK85AQ5P5d0LVldCLwQa5bZz+HMP6CctUlWOWiiVWoNBR9zy4cnLYtGGCERgFWsM33kgiDGJE2RNYeDVMopDRmLZyKWNP1nE=
  template:
    metadata:
      creationTimestamp: null
      name: mcpo-credentials
      namespace: mcpo
    type: Opaque

