apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  releaseName: postgres
  chart:
    spec:
      chart: postgresql
      version: 16.7.21
      interval: 10h # Interval for Helm chart updates
      sourceRef:
        kind: HelmRepository
        name: postgres
        namespace: postgres
  interval: 1h # Helm CRD drift detection interval
global:
  primary:
    service:
      type: LoadBalancer