# Postgres HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgres
  namespace: postgres
spec:
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  type: oci