# Postgres HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgresql
  namespace: postgresql
spec:
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci