apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: synology
spec:
  releaseName: synology-csi
  targetNamespace: synology
  interval: 1h # Helm CRD drift detection interval
  timeout: 15m
  chart:
    spec:
      chart: synology-csi
      version: 0.10.1
      interval: 10h # Interval for Helm chart updates
      sourceRef:
        kind: HelmRepository
        name: synology
        namespace: synology
  values:
    clientInfoSecret:
      clients:
        apiVersion: v1
        kind: Secret
        metadata:
          name: synology-csi-client-info
        stringData:
          client-info.yaml: |
            clients:
            - host: 192.168.68.67
              https: false
              password: z*mbts2C
              port: 5000
              username: k8s