apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  dependsOn:
    - name: sealed-secrets
      namespace: sealed-secrets
  interval: 15m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.86.2"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Tailscale operator configuration
    operator:
      # OAuth configuration - references the secret containing both client_id and client_secret
      # Create secret with: kubectl create secret generic operator-oauth --from-literal=client_id=... --from-literal=client_secret=...
      oauth:
        secretName: "operator-oauth"
      
    # RBAC configuration
    rbac:
      create: true
    
    serviceAccount:
      create: true
      name: "tailscale-operator"
    
    # Resource limits
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    
    # Node selector (optional)
    # nodeSelector: {}
    
    # Tolerations (optional)
    # tolerations: []
    
    # Affinity (optional)
    # affinity: {}
    
    # Pod security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    
    # Security context
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
