---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgARRk5sHife9XNXwOK7jNIgNLXCZpZPH9fW2QFb/aSDYd5bLeTcig4Wj1euGuG5tady709iST4ARzYxkkT8fAByBvcX/ywfhFoL2Dbo4zFN8nKMd3kfO5IGRqYHR+hJawojKhWvp/mv/PQyHZuRgXIHd8Ad69WgYqfrNAQDXFtUyzN9KWt+VCG3eGNKV9gmRHIH+T3tQe2inImvE7urumipeYZeQIjoG+1Y0gxNA3T527gvB8I87GlyTCxtludnqwHto6HYUpDMr7N3bHimClQeEgW4i5cNKgLjIZ45E1G3O8XKs6nWFUprms23ZlL/3W1EifbXhXtyZU0Pl979P5SPNlkEAy2pBdAb81CHzf4a9mTl/M1Zxr5AEohCgN6K804H5ZTTScIzcQOxCzGwzSvWsjZJaq6jxJZU4SL1tSk6vS+2x2TQjAUx8K8ig1t4n2GvVRrV03ysJdwYC3UKrxxB1WehImqq8OKAIv+hwFduDgdZm/qb4l9OgKaa2L5ox28nfebvhcVAh0xHfOtUYosexbXfyBVZ6r50AQLnN6PU/+ZjgyU+BUyUVzKiXinw3WgUG/Rin3wLwo/7DDJZFso8gqX9ilVgJ/bp96p7vzezUYXyBNU6Yy2Km2qXUpknSQRkHHeQIVsdulFdRU4zp4f1WxM2lircvWBqoUrjq7z0NyMCmkNFkEhjE6DwXJjvkvaQm8C7FS5btK+h97sutMLE4g==
    client_secret: AgBo3XkXP++8qx4hEgblWwtRvNH+vmm78lbxan9fX8+B+Ov1M9XOnKG3l5PCNKkkuVwpjRyviZvIivmQcryzSJehHlCYuWkTJDbvAJ4GvUOMXgnpcnWxRrvdxD8FIty5a8F/xufdCiHDeLE9s0Rb4FhnVs6VSo7wm3iag+uTbxPClvIotiVGT4VUmOex95OGY64j6YTiuL5aKLNuvzeAgIc9NfnRmreTmvqd2JqgirreRhyaMUSiorpvgOq//oYRjVQNZAqRDyVdTpbmlsBL9MtyfN0Di5HTwhAHtMgHVHjTxKM7TiBourkZPoYc4hkTwNuNa4kanNoT8h7VoUSCEjw12rorreE4aGXMa4XBuKAxU+z1U7ycgI78GOjAOJH71WyLd/DkRLuDCAzGmxRwCDY/FcWsdXR1W2Nn4YDFqIQ5DlAFf1EYb9gGpFrfc2QEDyr9Vh9phHWbeiQKebxIJ8lnoGPmM0CwWM5I5X8KnIjl7gKGtg18KpdtGXj2Aw7/PPjeBAeagdN5MWRu59gctlXarxc/uoR8K8XbbitXNjBfFquR3pE7TDaxTx/RfG565RxJB49YmyfjZUiyLfkMSBXqNiCSjE/oUtnG6ay/tqaVHm2qRp2xYtFcFDFR/8/kj3YNibmmRZDi/HExskAW5+OeHY82kL5DeZ6K54ZZtrdgiedUFHQ8fUzjKYhT4zXs2mrajoHW7dMr82335Dl4nvB36VKAfaObnqNnxsZ3zqQkBO73LCzV/P7mmHfq8I0SRD3CeyvyP4R4xX7T+57zH/US
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
