apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  releaseName: open-webui
  targetNamespace: open-webui
  interval: 1h # Helm CRD drift detection interval
  chart:
    spec:
      chart: open-webui
      version: 7.6.0 # Check https://helm.openwebui.com/ for latest version
      interval: 10h # Interval for Helm chart updates
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: open-webui
  values:
    # Disable embedded Ollama since we have a separate Ollama deployment
    ollama:
      enabled: false
    
    # Configure external Ollama URLs - pointing to your existing Ollama service
    ollamaUrls:
      - "http://ollama.ollama.svc.cluster.local:11434"
    
    # Disable pipelines for simpler setup (can be enabled later)
    pipelines:
      enabled: false
    
    # Disable Tika for now
    tika:
      enabled: false

    # Resource configuration
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 1Gi
    
    # Service configuration - using LoadBalancer to match your Ollama setup
    service:
      type: LoadBalancer
      port: 5050
      containerPort: 8080
    
    # Persistence for user data and conversations
    persistence:
      enabled: false
      # size: 5Gi
      # accessModes:
      #   - ReadWriteOnce
      # storageClass: "synology-csi-iscsi-retain"
    
    # # Environment variables
    # extraEnvVars:
    #   - name: WEBUI_AUTH
    #     value: "true" # Enable authentication
    #   - name: WEBUI_NAME
    #     value: "Open WebUI"
    #   - name: ENABLE_OPENAI_API
    #     value: "false" # Disable since we're using Ollama
    
    # # Security context
    # podSecurityContext:
    #   fsGroup: 1000
    
    # containerSecurityContext:
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   runAsNonRoot: true
    
    # Node selector (optional - uncomment if you want to run on specific nodes)
    # nodeSelector:
    #   kubernetes.io/arch: amd64
    
    # Ingress (disabled for now - using LoadBalancer)
    ingress:
      enabled: false
