apiVersion: v1
kind: Service
metadata:
  name: postgres-loadbalancer
  namespace: postgres
spec:
  type: LoadBalancer
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql
